# Generated by Django 4.2 on 2025-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
